#!/bin/bash


NAME="inside_kids"

DJANGODIR=/home/ubuntu/inside_kids

SOCKFILE=localhost:8000

USER=ubuntu

NUM_WORKERS=3

DJANGO_SETTINGS_MODULE=backend.settings

DJANGO_WSGI_MODULE=backend.wsgi



echo "Starting $NAME as `whoami`"



export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

export PYTHONPATH=$DJANGODIR:$PYTHONPATH



# RUNDIR=$(dirname $SOCKFILE)

# test -d $RUNDIR || mkdir -p $RUNDIR



exec /home/ubuntu/inside_kids/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \

  --name $NAME \

  --workers $NUM_WORKERS \

  --user=$USER \

  --bind=unix:$SOCKFILE \

  --log-level=debug \

  --log-file=-
